In [43]:
import numpy as np
import pandas as pd
input_file = "/Users/fengpengda/Desktop/wine_predict/uci-wine-quality/winequality-white3.csv"
df = pd.read_csv(input_file,header = 0,delimiter = ",") # 读取文件，以，作为分隔符
df = df._get_numeric_data() # 删除不是数字的行
numeric_headers = list(df.columns.values)
numpy_array = df.as_matrix()
print(numpy_array)
label_y = numpy_array[:,-1] # label集
print(label_y)
data_X = numpy_array[:,0:-1]  # 所有数据
print(data_X)


# 切分训练集和验证集
row,colume = data_X.shape
train_X = data_X[0:int(row * 0.7),:] # 训练集
train_y = label_y[0:int(row*0.7)]
test_X = data_X[int(row*0.7) + 1:,:] # 测试集
test_y = label_y[int(row*0.7) + 1:]

numeric_headers.reverse()
reverse_df = df[numeric_headers]

[[  7.     0.27   0.36 ...,   0.45   8.8    6.  ]
 [  6.3    0.3    0.34 ...,   0.49   9.5    6.  ]
 [  8.1    0.28   0.4  ...,   0.44  10.1    6.  ]
 ..., 
 [  6.5    0.24   0.19 ...,   0.46   9.4    6.  ]
 [  5.5    0.29   0.3  ...,   0.38  12.8    7.  ]
 [  6.     0.21   0.38 ...,   0.32  11.8    6.  ]]
[ 6.  6.  6. ...,  6.  7.  6.]
[[  7.     0.27   0.36 ...,   3.     0.45   8.8 ]
 [  6.3    0.3    0.34 ...,   3.3    0.49   9.5 ]
 [  8.1    0.28   0.4  ...,   3.26   0.44  10.1 ]
 ..., 
 [  6.5    0.24   0.19 ...,   2.99   0.46   9.4 ]
 [  5.5    0.29   0.3  ...,   3.34   0.38  12.8 ]
 [  6.     0.21   0.38 ...,   3.26   0.32  11.8 ]]
[ 5.  6.  6. ...,  6.  7.  6.]


In [40]:
from sklearn import preprocessing
normalized_X = preprocessing.normalize(data_X)
standardized_X = preprocessing.scale(data_X)

In [44]:
# 朴素贝叶斯
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(train_X,train_y)
print(model)

GaussianNB(priors=None)


In [45]:
predicted = model.predict(test_X)
expected = test_y

In [46]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

             precision    recall  f1-score   support

        3.0       0.07      0.50      0.12         2
        4.0       0.41      0.32      0.36        37
        5.0       0.51      0.51      0.51       394
        6.0       0.53      0.23      0.33       732
        7.0       0.29      0.76      0.43       262
        8.0       0.26      0.17      0.20        42

avg / total       0.47      0.40      0.39      1469

[[  1   0   0   1   0   0]
 [  1  12   9   5   9   1]
 [  6   7 202 118  60   1]
 [  4   9 151 172 386  10]
 [  1   1  26  26 200   8]
 [  2   0   8   2  23   7]]
